## **Generating Orthogonal Arrays**

In [16]:
import itertools
import numpy as np

def generate_orthogonal_array(n, k, s):
    # Generate all possible combinations of s levels for k columns
    all_combinations = list(itertools.product(range(s), repeat=k))

    # Select the first n rows to create the orthogonal array
    orthogonal_array = all_combinations[:n]

    return np.array(orthogonal_array)

def main():
    n = 6  # Number of runs (rows)
    s = 3  # Number of levels per factor

    for k in range(2, n):  # Number of factors (columns) from 2 to n
        oa = generate_orthogonal_array(n, k, s)
        print(f"Orthogonal Array (6 x {k}):")
        print(oa)
        print("\n")

if __name__ == "__main__":
    main()


Orthogonal Array (6 x 2):
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]


Orthogonal Array (6 x 3):
[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 1 0]
 [0 1 1]
 [0 1 2]]


Orthogonal Array (6 x 4):
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]]


Orthogonal Array (6 x 5):
[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 1 2]]




## **Generating Orthogonal Arrays without the itertools library**

In [17]:
import numpy as np

def generate_orthogonal_array(n, k, s):
    # Create an empty array to hold the orthogonal array
    orthogonal_array = np.zeros((n, k), dtype=int)

    # Fill the orthogonal array based on specific patterns to ensure orthogonality
    for i in range(k):
        for j in range(n):
            orthogonal_array[j][i] = (j + (i * j) // s) % s

    return orthogonal_array

def main():
    n = 6  # Number of runs (rows)
    s = 3  # Number of levels per factor

    # Iterate over a predefined range of factors (columns)
    for k in range(2, 6):  # Number of factors (columns) from 2 to 6
        oa = generate_orthogonal_array(n, k, s)
        print(f"Orthogonal Array (6 x {k}):")
        print(oa)
        print("\n")

if __name__ == "__main__":
    main()


Orthogonal Array (6 x 2):
[[0 0]
 [1 1]
 [2 2]
 [0 1]
 [1 2]
 [2 0]]


Orthogonal Array (6 x 3):
[[0 0 0]
 [1 1 1]
 [2 2 0]
 [0 1 2]
 [1 2 0]
 [2 0 2]]


Orthogonal Array (6 x 4):
[[0 0 0 0]
 [1 1 1 2]
 [2 2 0 1]
 [0 1 2 0]
 [1 2 0 2]
 [2 0 2 1]]


Orthogonal Array (6 x 5):
[[0 0 0 0 0]
 [1 1 1 2 2]
 [2 2 0 1 1]
 [0 1 2 0 1]
 [1 2 0 2 0]
 [2 0 2 1 2]]




*Author: Suhanee Hingorani*