## **Orthogonal Array Generation for the attributes of a Smartphone**

#**Features of the Smartphone:**

i. It has three battery lifes: Poor,Average,Good

ii. It has three price points: Low, Medium, High

Battery Life and Phone Price, each with 3 levels, the maximum number of combinations is 9.

We want to generate an orthogonal array that considers these factors, which will result in a **9x2 matrix (9 runs and 2 factors)**.


In [11]:
import itertools
import numpy as np

# Define the levels for each feature
battery_levels = ["Poor", "Average", "Good"]
price_levels = ["Low", "Medium", "High"]

def generate_orthogonal_array(n, k, s):
    # Generate all possible combinations of s levels for k columns
    all_combinations = list(itertools.product(range(s), repeat=k))

    # Select the first n rows to create the orthogonal array
    orthogonal_array = all_combinations[:n]

    return np.array(orthogonal_array)

def main():
    n = 9  # Number of runs (rows)
    k = 2  # Number of factors (columns)
    s = 3  # Number of levels per factor

    # Generate the orthogonal array
    oa = generate_orthogonal_array(n, k, s)

    print(f"Orthogonal Array (9 x 2):")
    print(oa)
    print("\nTranslated Levels:")

    # Translate numeric levels to actual feature levels
    for row in oa:
        battery = battery_levels[row[0]]
        price = price_levels[row[1]]
        print(f"Battery Life: {battery}, Phone Price: {price}")

if __name__ == "__main__":
    main()


Orthogonal Array (9 x 2):
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]

Translated Levels:
Battery Life: Poor, Phone Price: Low
Battery Life: Poor, Phone Price: Medium
Battery Life: Poor, Phone Price: High
Battery Life: Average, Phone Price: Low
Battery Life: Average, Phone Price: Medium
Battery Life: Average, Phone Price: High
Battery Life: Good, Phone Price: Low
Battery Life: Good, Phone Price: Medium
Battery Life: Good, Phone Price: High


We want to generate an orthogonal array that considers these factors, which will result in a **6x2 matrix (6 runs and 2 factors)**.

*Reducing the Orthogonal Array*


In [12]:
import itertools
import numpy as np

# Define the levels for each feature
battery_levels = ["Poor", "Average", "Good"]
price_levels = ["Low", "Medium", "High"]

def generate_orthogonal_array(n, k, s):
    # Generate all possible combinations of s levels for k columns
    all_combinations = list(itertools.product(range(s), repeat=k))

    # Select the first n rows to create the orthogonal array
    orthogonal_array = all_combinations[:n]

    return np.array(orthogonal_array)

def main():
    n = 6  # Number of runs (rows)
    k = 2  # Number of factors (columns)
    s = 3  # Number of levels per factor

    # Generate the orthogonal array
    oa = generate_orthogonal_array(n, k, s)

    print(f"Orthogonal Array (6 x 2):")
    print(oa)
    print("\nTranslated Levels:")

    # Translate numeric levels to actual feature levels
    for row in oa:
        battery = battery_levels[row[0]]
        price = price_levels[row[1]]
        print(f"Battery Life: {battery}, Phone Price: {price}")

if __name__ == "__main__":
    main()


Orthogonal Array (6 x 2):
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]]

Translated Levels:
Battery Life: Poor, Phone Price: Low
Battery Life: Poor, Phone Price: Medium
Battery Life: Poor, Phone Price: High
Battery Life: Average, Phone Price: Low
Battery Life: Average, Phone Price: Medium
Battery Life: Average, Phone Price: High


Orthogonal Array on adding **another smartphone:**

In [13]:
import itertools
import numpy as np

# Define the levels for each feature
battery_levels = ["Poor", "Average", "Good"]
price_levels = ["Low", "Medium", "High"]

def generate_orthogonal_array(n, k, s):
    # Generate all possible combinations of s levels for k columns
    all_combinations = list(itertools.product(range(s), repeat=k))

    # Select the first n rows to create the orthogonal array
    orthogonal_array = all_combinations[:n]

    return np.array(orthogonal_array)

def main():
    n = 6  # Number of runs (rows)
    k = 4  # Number of factors (columns), since we have 2 phones each with 2 factors (Battery Life and Phone Price)
    s = 3  # Number of levels per factor

    # Generate the orthogonal array
    oa = generate_orthogonal_array(n, k, s)

    print(f"Orthogonal Array (6 x 4):")
    print(oa)
    print("\nTranslated Levels:")

    # Translate numeric levels to actual feature levels for each phone
    for row in oa:
        battery1 = battery_levels[row[0]]
        price1 = price_levels[row[1]]
        battery2 = battery_levels[row[2]]
        price2 = price_levels[row[3]]
        print(f"Phone 1: Battery Life={battery1}, Phone Price={price1} | Phone 2: Battery Life={battery2}, Phone Price={price2}")

if __name__ == "__main__":
    main()


Orthogonal Array (6 x 4):
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]]

Translated Levels:
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Poor, Phone Price=Low
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Poor, Phone Price=Medium
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Poor, Phone Price=High
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Average, Phone Price=Low
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Average, Phone Price=Medium
Phone 1: Battery Life=Poor, Phone Price=Low | Phone 2: Battery Life=Average, Phone Price=High


*Author: Suhanee Hingorani*